AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "ChestCheck API — API Gateway + Lambda functions"

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues: [prod]

  OpenAiApiKey:
    Type: String
    NoEcho: true
    Description: Unused in v1 — kept for pipeline compatibility

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 256
    Architectures:
      - arm64
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        USERS_TABLE: !ImportValue
          Fn::Sub: "lb-${Environment}-users-table"
        HOUSEHOLDS_TABLE: !ImportValue
          Fn::Sub: "lb-${Environment}-households-table"
        CATEGORIES_TABLE: !ImportValue
          Fn::Sub: "lb-${Environment}-categories-table"
        TRANSACTIONS_TABLE: !ImportValue
          Fn::Sub: "lb-${Environment}-chest-transactions-table"
        KMS_KEY_ARN: !ImportValue
          Fn::Sub: "lb-${Environment}-kms-key-arn"

Resources:
  # -------------------------------------------------------
  # API Gateway
  # -------------------------------------------------------
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "lb-api-${Environment}"
      StageName: !Ref Environment
      Auth:
        DefaultAuthorizer: CognitoAuth
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          CognitoAuth:
            UserPoolArn: !ImportValue
              Fn::Sub: "lb-${Environment}-user-pool-arn"
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'https://leakingbuckets.goronny.com'"

  # -------------------------------------------------------
  # Shared Lambda execution role
  # -------------------------------------------------------
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "lb-lambda-role-${Environment}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: AppAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:BatchWriteItem
                  - dynamodb:BatchGetItem
                Resource:
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/lb-*-${Environment}"
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/lb-*-${Environment}/index/*"
              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:Encrypt
                  - kms:GenerateDataKey
                Resource:
                  - !ImportValue
                    Fn::Sub: "lb-${Environment}-kms-key-arn"

  # -------------------------------------------------------
  # Lambda Functions
  # -------------------------------------------------------
  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "lb-health-${Environment}"
      Handler: handlers/health.handler
      CodeUri: ../backend/
      Role: !GetAtt LambdaRole.Arn
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /health
            Method: GET
            Auth:
              Authorizer: NONE

  UserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "lb-user-${Environment}"
      Handler: handlers/user.handler
      CodeUri: ../backend/
      Role: !GetAtt LambdaRole.Arn
      Events:
        GetMe:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /me
            Method: GET
        JoinHousehold:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /household/join
            Method: POST

  CategoriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "lb-categories-${Environment}"
      Handler: handlers/categories.handler
      CodeUri: ../backend/
      Role: !GetAtt LambdaRole.Arn
      Events:
        List:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /categories
            Method: GET
        Create:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /categories
            Method: POST
        Update:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /categories/{categoryId}
            Method: PUT

  TransactionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "lb-transactions-${Environment}"
      Handler: handlers/transactions.handler
      CodeUri: ../backend/
      Role: !GetAtt LambdaRole.Arn
      Events:
        Create:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /transactions
            Method: POST
        List:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /transactions
            Method: GET
        Delete:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /transactions/{transactionId}
            Method: DELETE

  SummaryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "lb-summary-${Environment}"
      Handler: handlers/summary.handler
      CodeUri: ../backend/
      Role: !GetAtt LambdaRole.Arn
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /summary
            Method: GET

  DataFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "lb-data-${Environment}"
      Handler: handlers/data.handler
      CodeUri: ../backend/
      Role: !GetAtt LambdaRole.Arn
      Timeout: 60
      Events:
        DeleteAll:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /data
            Method: DELETE

Outputs:
  ApiUrl:
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
    Export:
      Name: !Sub "lb-${Environment}-api-url"
