AWSTemplateFormatVersion: "2010-09-09"
Description: "Leaky-Buckets Auth — Cognito User Pool (2-user household)"

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues: [prod]

Resources:
  # -------------------------------------------------------
  # Cognito User Pool — email + password, no social logins
  # -------------------------------------------------------
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "lb-users-${Environment}"
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      MfaConfiguration: "OFF"
      Policies:
        PasswordPolicy:
          MinimumLength: 12
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      DeletionProtection: ACTIVE
      UserPoolTags:
        App: leaky-buckets
        Environment: !Ref Environment

  # -------------------------------------------------------
  # App Client — SPA-friendly (no secret)
  # -------------------------------------------------------
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "lb-web-${Environment}"
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED
      AccessTokenValidity: 60        # minutes
      IdTokenValidity: 60
      RefreshTokenValidity: 30        # days
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days
      SupportedIdentityProviders:
        - COGNITO

Outputs:
  UserPoolId:
    Value: !Ref UserPool
    Export:
      Name: !Sub "lb-${Environment}-user-pool-id"

  UserPoolArn:
    Value: !GetAtt UserPool.Arn
    Export:
      Name: !Sub "lb-${Environment}-user-pool-arn"

  UserPoolClientId:
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub "lb-${Environment}-user-pool-client-id"
