AWSTemplateFormatVersion: "2010-09-09"
Description: "ChestCheck Foundation — KMS key, S3 bucket, DynamoDB tables"

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues: [prod]

Resources:
  # -------------------------------------------------------
  # KMS — single key for all at-rest encryption
  # -------------------------------------------------------
  AppKey:
    Type: AWS::KMS::Key
    Properties:
      Description: ChestCheck encryption key
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowRootAccount
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"

  AppKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/lb-${Environment}"
      TargetKeyId: !Ref AppKey

  # -------------------------------------------------------
  # S3 — SAM deployment artifacts bucket
  # -------------------------------------------------------
  SamArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "lb-sam-artifacts-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: App
          Value: chestcheck
        - Key: Environment
          Value: !Ref Environment

  # -------------------------------------------------------
  # DynamoDB — Users (userId → householdId mapping)
  # -------------------------------------------------------
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "lb-users-${Environment}"
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref AppKey
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      Tags:
        - Key: App
          Value: chestcheck

  # -------------------------------------------------------
  # DynamoDB — Households
  # -------------------------------------------------------
  HouseholdsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "lb-households-${Environment}"
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref AppKey
      AttributeDefinitions:
        - AttributeName: householdId
          AttributeType: S
      KeySchema:
        - AttributeName: householdId
          KeyType: HASH
      Tags:
        - Key: App
          Value: chestcheck

  # -------------------------------------------------------
  # DynamoDB — Categories (Treasure Chests)
  # -------------------------------------------------------
  CategoriesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "lb-categories-${Environment}"
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref AppKey
      AttributeDefinitions:
        - AttributeName: householdId
          AttributeType: S
        - AttributeName: categoryId
          AttributeType: S
      KeySchema:
        - AttributeName: householdId
          KeyType: HASH
        - AttributeName: categoryId
          KeyType: RANGE
      Tags:
        - Key: App
          Value: chestcheck

  # -------------------------------------------------------
  # DynamoDB — Transactions (NEW — householdId + sk)
  # -------------------------------------------------------
  ChestTransactionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "lb-chest-transactions-${Environment}"
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref AppKey
      AttributeDefinitions:
        - AttributeName: householdId
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: householdId
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      Tags:
        - Key: App
          Value: chestcheck

  # =======================================================
  # LEGACY TABLES — kept temporarily for cross-stack export
  # dependencies. Will be removed in a follow-up deploy.
  # =======================================================
  TransactionsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: !Sub "lb-transactions-${Environment}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: monthKey
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: byMonth
          KeySchema:
            - AttributeName: monthKey
              KeyType: HASH
            - AttributeName: sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  MerchantsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: !Sub "lb-merchants-${Environment}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: merchantName
          AttributeType: S
      KeySchema:
        - AttributeName: merchantName
          KeyType: HASH

  BucketsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: !Sub "lb-buckets-${Environment}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: bucketId
          AttributeType: S
      KeySchema:
        - AttributeName: bucketId
          KeyType: HASH

  MonthlySummariesTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: !Sub "lb-monthly-summaries-${Environment}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: monthKey
          AttributeType: S
      KeySchema:
        - AttributeName: monthKey
          KeyType: HASH

  LiveExpensesTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: !Sub "lb-live-expenses-${Environment}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

  RecurringBillsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: !Sub "lb-recurring-bills-${Environment}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

  PaystubsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: !Sub "lb-paystubs-${Environment}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: paystubId
          AttributeType: S
      KeySchema:
        - AttributeName: paystubId
          KeyType: HASH

  # LEGACY S3 — uploads bucket (kept for export dependency)
  UploadsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub "lb-uploads-${Environment}-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  KmsKeyArn:
    Value: !GetAtt AppKey.Arn
    Export:
      Name: !Sub "lb-${Environment}-kms-key-arn"

  # --- New ChestCheck tables ---
  UsersTableName:
    Value: !Ref UsersTable
    Export:
      Name: !Sub "lb-${Environment}-users-table"

  HouseholdsTableName:
    Value: !Ref HouseholdsTable
    Export:
      Name: !Sub "lb-${Environment}-households-table"

  CategoriesTableName:
    Value: !Ref CategoriesTable
    Export:
      Name: !Sub "lb-${Environment}-categories-table"

  ChestTransactionsTableName:
    Value: !Ref ChestTransactionsTable
    Export:
      Name: !Sub "lb-${Environment}-chest-transactions-table"

  # --- Legacy exports (kept until API stack stops importing them) ---
  TransactionsTableName:
    Value: !Ref TransactionsTable
    Export:
      Name: !Sub "lb-${Environment}-transactions-table"

  MerchantsTableName:
    Value: !Ref MerchantsTable
    Export:
      Name: !Sub "lb-${Environment}-merchants-table"

  BucketsTableName:
    Value: !Ref BucketsTable
    Export:
      Name: !Sub "lb-${Environment}-buckets-table"

  MonthlySummariesTableName:
    Value: !Ref MonthlySummariesTable
    Export:
      Name: !Sub "lb-${Environment}-monthly-summaries-table"

  PaystubsTableName:
    Value: !Ref PaystubsTable
    Export:
      Name: !Sub "lb-${Environment}-paystubs-table"

  LiveExpensesTableName:
    Value: !Ref LiveExpensesTable
    Export:
      Name: !Sub "lb-${Environment}-live-expenses-table"

  RecurringBillsTableName:
    Value: !Ref RecurringBillsTable
    Export:
      Name: !Sub "lb-${Environment}-recurring-bills-table"

  UploadsBucketName:
    Value: !Ref UploadsBucket
    Export:
      Name: !Sub "lb-${Environment}-uploads-bucket"

  UploadsBucketArn:
    Value: !GetAtt UploadsBucket.Arn
    Export:
      Name: !Sub "lb-${Environment}-uploads-bucket-arn"
