AWSTemplateFormatVersion: "2010-09-09"
Description: "ChestCheck Foundation — KMS key, S3 bucket, DynamoDB tables"

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues: [prod]

Resources:
  # -------------------------------------------------------
  # KMS — single key for all at-rest encryption
  # -------------------------------------------------------
  AppKey:
    Type: AWS::KMS::Key
    Properties:
      Description: ChestCheck encryption key
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowRootAccount
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"

  AppKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/lb-${Environment}"
      TargetKeyId: !Ref AppKey

  # -------------------------------------------------------
  # S3 — SAM deployment artifacts bucket
  # -------------------------------------------------------
  SamArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "lb-sam-artifacts-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: App
          Value: chestcheck
        - Key: Environment
          Value: !Ref Environment

  # -------------------------------------------------------
  # DynamoDB — Users (userId → householdId mapping)
  # -------------------------------------------------------
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "lb-users-${Environment}"
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref AppKey
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      Tags:
        - Key: App
          Value: chestcheck

  # -------------------------------------------------------
  # DynamoDB — Households
  # -------------------------------------------------------
  HouseholdsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "lb-households-${Environment}"
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref AppKey
      AttributeDefinitions:
        - AttributeName: householdId
          AttributeType: S
      KeySchema:
        - AttributeName: householdId
          KeyType: HASH
      Tags:
        - Key: App
          Value: chestcheck

  # -------------------------------------------------------
  # DynamoDB — Categories (Treasure Chests)
  # -------------------------------------------------------
  CategoriesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "lb-categories-${Environment}"
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref AppKey
      AttributeDefinitions:
        - AttributeName: householdId
          AttributeType: S
        - AttributeName: categoryId
          AttributeType: S
      KeySchema:
        - AttributeName: householdId
          KeyType: HASH
        - AttributeName: categoryId
          KeyType: RANGE
      Tags:
        - Key: App
          Value: chestcheck

  # -------------------------------------------------------
  # DynamoDB — Transactions (householdId + sk)
  # -------------------------------------------------------
  ChestTransactionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "lb-chest-transactions-${Environment}"
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref AppKey
      AttributeDefinitions:
        - AttributeName: householdId
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: householdId
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      Tags:
        - Key: App
          Value: chestcheck

Outputs:
  KmsKeyArn:
    Value: !GetAtt AppKey.Arn
    Export:
      Name: !Sub "lb-${Environment}-kms-key-arn"

  # --- New ChestCheck tables ---
  UsersTableName:
    Value: !Ref UsersTable
    Export:
      Name: !Sub "lb-${Environment}-users-table"

  HouseholdsTableName:
    Value: !Ref HouseholdsTable
    Export:
      Name: !Sub "lb-${Environment}-households-table"

  CategoriesTableName:
    Value: !Ref CategoriesTable
    Export:
      Name: !Sub "lb-${Environment}-categories-table"

  ChestTransactionsTableName:
    Value: !Ref ChestTransactionsTable
    Export:
      Name: !Sub "lb-${Environment}-chest-transactions-table"
