AWSTemplateFormatVersion: "2010-09-09"
Description: "Leaky-Buckets Frontend — S3 static site + CloudFront CDN"

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues: [prod]

  DomainName:
    Type: String
    Default: leakingbuckets.goronny.com
    Description: Custom domain name for the frontend

  AcmCertificateArn:
    Type: String
    Default: arn:aws:acm:us-east-1:123525499627:certificate/6b03975e-2c39-4656-8358-94dbbe6003b4
    Description: ACM certificate ARN for the custom domain (must be in us-east-1)

Resources:
  # -------------------------------------------------------
  # S3 — static site bucket (private, accessed via CloudFront)
  # -------------------------------------------------------
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "lb-frontend-${Environment}-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: App
          Value: leaky-buckets
        - Key: Environment
          Value: !Ref Environment

  # -------------------------------------------------------
  # CloudFront Origin Access Control
  # -------------------------------------------------------
  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "lb-frontend-oac-${Environment}"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # -------------------------------------------------------
  # CloudFront Distribution
  # -------------------------------------------------------
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub "Leaky Buckets (${Environment})"
        DefaultRootObject: index.html
        Aliases:
          - !Ref DomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            OriginAccessControlId: !Ref OriginAccessControl
            S3OriginConfig:
              OriginAccessIdentity: ""
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          DefaultTTL: 86400
          MaxTTL: 31536000
          MinTTL: 0
        # SPA routing — serve index.html for all 404s
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 10
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 10
        PriceClass: PriceClass_100
        HttpVersion: http2and3
      Tags:
        - Key: App
          Value: leaky-buckets
        - Key: Environment
          Value: !Ref Environment

  # -------------------------------------------------------
  # Bucket policy — allow CloudFront to read
  # -------------------------------------------------------
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFront
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${FrontendBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${Distribution}"

Outputs:
  FrontendBucketName:
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub "lb-${Environment}-frontend-bucket"

  CloudFrontDistributionId:
    Value: !Ref Distribution
    Export:
      Name: !Sub "lb-${Environment}-cloudfront-id"

  CloudFrontDomainName:
    Value: !GetAtt Distribution.DomainName
    Export:
      Name: !Sub "lb-${Environment}-cloudfront-domain"

  FrontendUrl:
    Value: !Sub "https://${Distribution.DomainName}"
